// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkvwiclfwgvlxsasrhqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrdndpY2xmd2d2bHhzYXNyaHF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MjIxMDAsImV4cCI6MjA2MTQ5ODEwMH0.xu3YaNZDjfBaaLnsByFA_yQPJw_7P2mk7rdItiMc0wU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);